---
- name: Include os-specific tasks
  ansible.builtin.include_tasks: '{{ ansible_facts.os_family | lower }}.yml'

- name: Ensure Visual Studio Code is installed
  ansible.builtin.package:
    name: code
    state: present
