---
- name: Include os-specific tasks (redhat-family)
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_facts.os_family|lower == "redhat"

- name: Include os-specific tasks (debian-family)
  ansible.builtin.include_tasks: debian.yml
  when: ansible_facts.os_family|lower == "debian"

- name: Ensure Visual Studio Code is installed
  ansible.builtin.package:
    name: code
    state: present