---
- name: Import Visual Studio Code gpg key
  ansible.builtin.rpm_key:
    key: '{{ vscode_gpg_key_url }}'
    fingerprint: '{{ vscode_gpg_key_fingerpint }}'

- name: Ensure Visual Studio Code repository exists
  ansible.builtin.yum_repository:
    name: code
    description: Visual Studio Code
    baseurl: '{{ vscode_rpm_repository_url }}'
    enabled: true
    gpgcheck: true
    gpgkey: '{{ vscode_gpg_key_url }}'