---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Ensure gpg is installed
      ansible.builtin.apt:
        name: gnupg
        update_cache: true
        force_apt_get: true
      when: ansible_facts.os_family | lower == "debian"

  tasks:
    - name: "Include egdoc.vscode"
      ansible.builtin.include_role:
        name: "egdoc.vscode"
